# Generated by Django 5.1.15 on 2026-04-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_housekeeping_log_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(blank=True, default='', max_length=20)),
                ('year', models.CharField(blank=True, default='', max_length=4)),
                ('data', models.JSONField(help_text='Array of housekeeping log rows')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Housekeeping submission',
                'verbose_name_plural': 'Housekeeping submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(blank=True, default='', max_length=20)),
                ('year', models.CharField(blank=True, default='', max_length=4)),
                ('data', models.JSONField(help_text='Array of timesheet rows')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timesheet submission',
                'verbose_name_plural': 'Timesheet submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
