# Generated by Django 5.1.15 on 2026-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activehousekeeping_activetimesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='activehousekeeping',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='activehousekeeping',
            name='pers_nr',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activetimesheet',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='activetimesheet',
            name='pers_nr',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='housekeepingsubmission',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='housekeepingsubmission',
            name='pers_nr',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='timesheetsubmission',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='timesheetsubmission',
            name='pers_nr',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
